export const HOME_PRODUCT_WOMAN = "HOME_PRODUCT_WOMAN"
export const HOME_PRODUCT_MAN = "HOME_PRODUCT_MAN"
export const PRODUCTS = "PRODUCTS"
export const PRODUCT = "PRODUCT"

export const LOAD_PRODUCT = "LOAD_PRODUCT"
export const FILTER_PRODUCTS = "FILTER_PRODUCTS"
export const LOAD_CATEGORIES = "LOAD_CATEGORIES"
export const UPDATE_FILTERS = "UPDATE_FILTERS"